spring:
  application:
    name: apollo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.102:3306/apollo?useSSL=false
    username: breelynn
    password: breelynn
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml
    min-response-size: 1024
